[package]
name = "arc_parser"
version = "0.2.0"
edition = "2021"

[lib]
name = "arc_parser"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.10.2"
clap = "4.4.8"
colored = "2.0"
structopt = "0.3"